version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
