version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn checkstyle:check compile
      - run: mvn clean verify

  upload-to-codecov:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Prepare Code Coverage Report
          command: mvn test jacoco:report
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Checkstyle Code Analysis
          command: mvn checkstyle:check || true

workflows:
  version: 2
  build-test-and-upload:
    jobs:
      - build-and-test
      - upload-to-codecov:
          requires:
            - build-and-test
          filters:
            branches:
              only: master