version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
      - codecov/upload:
          token: ${CODECOV_TOKEN}

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build:
          filters:
            branches:
              only: master
