version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
